# source_path|target_folder_name
/root/finetuning/cycloneCopilot|CycloneCopilot
/root/projectResearch|projectResearch
/root/SEIA-MOD|SEIA-MOD
/root/SEIA-MOD-ASSET|SEIA-MOD-ASSET
/root/Cyclone_next|Cyclone_next
/root/PINN-ENV|PINN-ENV
/root/exTweather-hazard|exTweather-hazard
